[package]
name = "ironrdp-rail"
version = "0.1.0"
readme = "README.md"
description = "RemoteApp (RAIL) static channel implemented as described in MS-RDPERP"
edition.workspace = true
rust-version = "1.89"
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.2" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.9" } # public
ironrdp-svc = { path = "../ironrdp-svc", version = "0.8" } # public
bitflags = "2.11"
tracing = { version = "0.1", features = ["log"] }

[lints]
workspace = true
